import Head from 'next/head'
import Link from 'next/link'
import { useMoralis } from 'react-moralis'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { authenticate, isAuthenticated, account } = useMoralis()

  if (!isAuthenticated || !account) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div className="h-screen w-screen flex items-center justify-center">
            <Head>
              <title>Moralis IO </title>
              <meta
                name="description"
                content="A basic tutorial of Moralis IO Login"
              />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <button
              onClick={() => authenticate()}
              className="px-7 py-4 text-xl rounded-xl bg-yellow-300 animate-pulse"
            >
              Login using Metamask
            </button>
          </div>
        </main>
      </div>
    )
  }

  return (
    <div>
      <h1>Welcome {account}</h1>
      <Link href="dashboard">Dashboard</Link>
    </div>
  )
}
